Repository ucsb-cs156-w24/proj-organic-w24-6pm-4, pull requests merged in 2024-03, with the labels that each got.

#65 EPIC: School and Term validations - B1
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
Labels: FIXME - Peer CR, FIXME - See comment

#73 DD EPIC 1 - B2 and B3
  src/main/java/edu/ucsb/cs156/organic/controllers/SchoolsController.java
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/test/java/edu/ucsb/cs156/organic/controllers/SchoolsControllerTests.java
Labels: 20

#72 BT: EPIC Schools Frontend
  frontend/src/App.js
  frontend/src/fixtures/SchoolsFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Schools/SchoolsEditForm.js
  frontend/src/main/components/Schools/SchoolsForm.js
  frontend/src/main/components/Schools/SchoolsTable.js
  frontend/src/main/pages/Schools/SchoolsCreatePage.js
  frontend/src/main/pages/Schools/SchoolsEditPage.js
  frontend/src/main/pages/Schools/SchoolsIndexPage.js
  frontend/src/main/utils/SchoolsUtils.js
  frontend/src/stories/components/Schools/SchoolsEditForm.stories.js
  frontend/src/stories/components/Schools/SchoolsForm.stories.js
  frontend/src/stories/components/Schools/SchoolsTable.stories.js
  frontend/src/stories/pages/Schools/SchoolsCreatePage.stories.js
  frontend/src/stories/pages/Schools/SchoolsEditPage.stories.js
  frontend/src/stories/pages/Schools/SchoolsIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Schools/SchoolsEditForm.test.js
  frontend/src/tests/components/Schools/SchoolsForm.test.js
  frontend/src/tests/components/Schools/SchoolsTable.test.js
  frontend/src/tests/pages/Schools/SchoolsCreatePage.test.js
  frontend/src/tests/pages/Schools/SchoolsEditPage.test.js
  frontend/src/tests/pages/Schools/SchoolsIndexPage.test.js
  frontend/src/tests/utils/SchoolsUtils.test.js
Labels: 20

#64 fixed footer typo
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
Labels: 5

#67 DJ-Issue #7, Last Online in User Profile Defaults to Wrong Date Fix
  src/main/java/edu/ucsb/cs156/organic/controllers/UserInfoController.java
  src/main/java/edu/ucsb/cs156/organic/entities/User.java
  src/test/java/edu/ucsb/cs156/organic/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/testconfig/MockCurrentUserServiceImpl.java
Labels: 5

#70 LZ - Fix EPIC 2 B1, B2 and B3 Endpoint Definitions
  frontend/src/App.js
  frontend/src/fixtures/courseFixtures.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Utils/CourseUtils.js
  frontend/src/main/pages/CourseCreatePage.js
  frontend/src/main/pages/CourseEditPage.js
  frontend/src/main/pages/CourseIndexPage.js
  frontend/src/stories/components/Courses/CourseForm.stories.js
  frontend/src/stories/components/Courses/CourseTable.stories.js
  frontend/src/stories/pages/CourseCreatePage.stories.js
  frontend/src/stories/pages/CourseEditPage.stories.js
  frontend/src/stories/pages/CourseIndexPage.stories.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  frontend/src/tests/components/Utils/CourseUtils.test.js
  frontend/src/tests/pages/CourseCreatePage.test.js
  frontend/src/tests/pages/CourseEditPage.test.js
  frontend/src/tests/pages/CourseIndexPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 20

#75 LZ - Complete EPIC 2 F5 and Fix Storybook Entries of Course Table and Pages
  .gitignore
  frontend/src/App.js
  frontend/src/main/components/Courses/StaffForm.js
  frontend/src/main/pages/CourseIndexPage.js
  frontend/src/main/pages/StaffCreatePage.js
  frontend/src/stories/components/Courses/StaffForm.stories.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Courses/StaffForm.test.js
  frontend/src/tests/pages/StaffCreatePage.test.js
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorAppConfig.java
  src/main/resources/db/migration/changes/0003_CreateUsersTable.json
  src/test/java/edu/ucsb/cs156/organic/interceptors/RoleUserInterceptorTests.java
Labels: 10
